### ISSUE TITLE
看了源码 好像不支持缓存呢  也没有把访问的日志打印  哈哈 不过可以加上去 楼主还是很厉害的

### ISSUE THREAD

**Issue by liuwen370494581** [lygttpod/RxHttpUtils#1]

**Comment by wl386123298** [comment]
缓存可以直接通过拦截器去做缓存操作的！

**Comment by liuwen370494581** [comment]
是的  可以在源码里面加上去的 我已经加上去了   只是给楼主提出来

**Comment by lygttpod** [comment]
@liuwen370494581 @wl386123298 
1、日志打印  有的  用的默认的  可以打印请求参数 请求头  返回接口  只是没做定制打印
2、缓存这块确实还没加，目前项目中没用的，就没直接加上去了，不过后期可以考虑会加上去的

谢谢提供的建议！

**Comment by liuwen370494581** [comment]
期待楼主的下一次上传和下载的封装

**Comment by okadaNana** [comment]
@wl386123298 @liuwen370494581 请问缓存需要怎么实现啊？拦截器中需要加上什么东西呢？

**Comment by liuwen370494581** [comment]
楼主 上传和下载 什么时候封装呢

**Comment by lygttpod** [comment]
@liuwen370494581 首先谢谢你一直关注着更新的动态，上传和下载相对麻烦一点，加上最近有点忙，还没来得及处理，等忙完这段时间会抽时间封装一下的，着急用的话可以先参照网上已有的方法自己去实现一个，我这边也会尽快完善这块内容。

**Comment by yanddongdong** [comment]
楼主能不能建立一个qq群  有啥问题都可以在群里讨论 我看了这代码 有很多的疑问  可是又没办法问

**Comment by lygttpod** [comment]
@liuwen370494581 新版本2.0.5添加多图片上传，请查看demo或者升级说明[v2.0.5](https://github.com/lygttpod/RxHttpUtils/releases/tag/2.0.5)
