### ISSUE TITLE
支持多文件上传吗

### ISSUE THREAD

**Issue by cccfly-bake** [lygttpod/RxHttpUtils#10]
如题

**Comment by lygttpod** [comment]
暂时只支持单文件，需要多文件的可以把单文件上传的参数修改一下就行了，过段时间会加上多文件上传功能

**Comment by cccfly-bake** [comment]
建议：上传进度拦截器，回调增加；失败重试机制增加。多谢大佬

**Comment by lygttpod** [comment]
@dyfan 新版本2.0.5添加多图片上传，请查看demo或者升级说明[v2.0.5](https://github.com/lygttpod/RxHttpUtils/releases/tag/2.0.5)
