### ISSUE TITLE
compile 'com.github.lygttpod:RxHttpUtils:2.0.4'下载问题

### ISSUE THREAD

**Issue by wyy16318** [lygttpod/RxHttpUtils#11]
你这个  compile 'com.github.lygttpod:RxHttpUtils:2.0.4'   是替代类库的libray的吗？为何一直下载不下来。编译通过不了。

**Comment by lygttpod** [comment]
![image](https://user-images.githubusercontent.com/11826777/34663666-d14b6530-f492-11e7-89ee-717255268725.png)

**Comment by wyy16318** [comment]
我试了不行那个RxHttpUtils-2.0.4-sources.jar 编译不过不知道为啥。

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}






dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    testCompile 'junit:junit:4.12'
   // compile project(':library')
    compile 'com.zhihu.android:matisse:0.4.3'
    compile 'com.github.bumptech.glide:glide:3.8.0'
    compile 'com.zxy.android:tiny:0.1.0'
    compile 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.4@aar'
    compile 'com.github.lygttpod:RxHttpUtils:2.0.4'
}

**Comment by lygttpod** [comment]
现在可以下载了吗
