### ISSUE TITLE
当请求出错会自动弹出错误信息的Toast？

### ISSUE THREAD

**Issue by MrGlaucus** [lygttpod/RxHttpUtils#12]
如果是的话如何去除？因为弹出信息为中文，APP是用的英文，所以会很违和

**Comment by lygttpod** [comment]
https://github.com/lygttpod/RxHttpUtils/blob/2.x/library/src/main/java/com/allen/library/exception/ApiException.java
所有错误信息在这个文件里边，可以根据自己需求改为英文即可，或者直接屏蔽吐司

**Comment by MrGlaucus** [comment]
请问如何屏蔽Toast，看了一下README没看到相关配置，另外我是使用的Gradle配置依赖，所以没法修改源码

**Comment by lygttpod** [comment]
@MrGlaucus 2.0.5版本已添加隐藏toast的方法，请看demo或者升级说明[2.0.5](https://github.com/lygttpod/RxHttpUtils/releases/tag/2.0.5)
