### ISSUE TITLE
取消请求的问题

### ISSUE THREAD

**Issue by LLQQHH** [lygttpod/RxHttpUtils#13]
这个方法：是取消所有请求，可能存在你快速点击去下个界面，上一个界面还在请求。这个时候你从下一个界面返回上一个界面的话，上一个界面请求就会被取消，这样体验不好。请问有没有只取消当前activity界面的请求的方法。 
  @Override
    protected void onDestroy() {
        super.onDestroy();
        //取消所有请求
        RxHttpUtils.cancelAllRequest();
    }

**Comment by lygttpod** [comment]
```
可以在回调中重写这个方法，把返回的Disposable 对象放到基类的集合中，统一管理处理，就可以解决你描述的问题了
                            @Override
                            public void doOnSubscribe(Disposable d) {
                                super.doOnSubscribe(d);
                            }
```
