### ISSUE TITLE
解析的问题

### ISSUE THREAD

**Issue by yanddongdong** [lygttpod/RxHttpUtils#17]
楼主 为什么我用了DataObserver 总是报解析错误，
  RxHttpUtils.createApi(ApiService.class)
                        .geBannerData()
                        .compose(Transformer.<BaseData<BannerBean>>switchSchedulers())
                        .subscribe(new DataObserver<BannerBean>() {
                            @Override
                            protected void onError(String errorMsg) {
                            }

                            @Override
                            protected void onSuccess(BannerBean data) {
                                String a = data.getData().get(0).getImg();
                            }
                        });

返回的json：
 /**
     * status : success
     * message :
     * data : [{"img":"http://orr4xduaa.bkt.clouddn.com/5a5daf4fa7196.jpg","link":""},{"img":"http://orr4xduaa.bkt.clouddn.com/5a5daf0b41d90.png","link":""}]
     * code : 200
     * token : 53egcib14n0i3vngmr7nd0vvt7
     */

bean：
 private List<DataBean> data;

    public List<DataBean> getData() {
        return data;
    }

    public void setData(List<DataBean> data) {
        this.data = data;
    }

    public static class DataBean {
        /**
         * img : http://orr4xduaa.bkt.clouddn.com/5a5daf4fa7196.jpg
         * link :
         */

        private String img;
        private String link;

**Comment by yanddongdong** [comment]
可以的话 能不能留下qq 我加您

**Comment by lygttpod** [comment]
@yanddongdong 460605805

**Comment by Mycircle** [comment]
提个建议，添加下自定义解析工厂类，用于处理接口返回异常数据。
