### ISSUE TITLE
cancelAllRequest和addDisposable的问题

### ISSUE THREAD

**Issue by FlogFly** [lygttpod/RxHttpUtils#18]
demo中因为只有一个activity，所以直接在请求接口后，在ondestory中调用cancelAllRequest方法，解除订阅，但是如果有多个activity，用的都是默认的在APP.java中的配置，又因为你的默认的RxHttpUtil是单例模式，用的是同一个private static List<Disposable> disposables; 这个list，这时候比如关闭了其中一个activity，你就没法直接调用cancelAllRequest了。因为就会把存在的其他的activity里面的订阅也给取消。

PS:不需要使用List<Disposable>这种，还要去遍历一个个取消，有现成的CompositeDisposable，添加进去一个个Disposable后，对CompositeDisposable取消订阅就可以。

**Comment by lygttpod** [comment]
多谢提供建议，后边会逐步优化

**Comment by lygttpod** [comment]
关于取消请求的问题已修复，请使用最新版本   查看 [更新日志](https://github.com/lygttpod/RxHttpUtils/releases)
