### ISSUE TITLE
建议及问题

### ISSUE THREAD

**Issue by wl386123298** [lygttpod/RxHttpUtils#2]
1、我在GET这个接口(http://www.qingniantuzhai.com/api/posts/3067?comments=3)  的时候给我重定向到另外一个网址去了，但是在浏览器请求就完全ok
2、处理一些loading框或者其他的loading方式的时候能否暴露接口便于去扩展。
3、貌似没有发现自动取消请求的操作！

**Comment by lygttpod** [comment]
@wl386123298  
1、第一个问题需要自己添加baseUrl,不添加的话默认会有一个测试地址 是我demo测试用的，通过getInstance(your_base_url)去添加你的baseUrl
2、loading只需传入一个Dialog类型的loading就行，想实现炫酷的loading显示只需自己实现好loading类即可 传入就行了
3、目前确实没加取消请求的操作，后续会加上去的；

谢谢提意见！

**Comment by wl386123298** [comment]
@lygttpod baseUrl我已经加了，上日志吧！

>  D/OkHttp: --> GET http://www.qingniantuzhai.com/posts/3067?comments=3 http/1.1
 D/OkHttp: Authorization: 
 D/OkHttp: Version: 1.0
 D/OkHttp: Terminal: 0
 D/OkHttp: X-Request-Id: ffffffff-82c9-0969-d9e9-d3974bb4b683
 D/OkHttp: User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0.1; ONE E1001 Build/MMB29M)
 D/OkHttp: --> END GET
 D/OkHttp: <-- 200 OK http://www.qingniantuzhai.com/posts/3067.html (229ms)

**Comment by lygttpod** [comment]
@wl386123298 嗯 ，后边会扩展这块的

**Comment by StormChen94** [comment]
在adapter中使用的话会把itemclick拦截掉

**Comment by lygttpod** [comment]
@streamingchen 大兄弟，issues发错地方了吧  [SuperTextView](https://github.com/lygttpod/SuperTextView)。。。在adapter中使用的话，需要取消点击水波扩散的属性即sUseRipple="false"

**Comment by lygttpod** [comment]
@wl386123298 
### 1、你说的关于loading不仅限于继承dialog的问题在最新版本中已经提供解决方案，可以为Transformer添加如下方法，实现MVP模式中V层控制UI展示的方法
```
    /**
     * 带参数  显示loading对话框
     * @param view MVP模式中的V层
     * @param <T>    泛型
     * @return 返回Observable
     */
    public static <T> ObservableTransformer<T, T> switchSchedulers(final View view) {
        return new ObservableTransformer<T, T>() {
            @Override
            public ObservableSource<T> apply(@NonNull Observable<T> upstream) {
                return upstream
                        .subscribeOn(Schedulers.io())
                        .unsubscribeOn(Schedulers.io())
                        .doOnSubscribe(new Consumer<Disposable>() {
                            @Override
                            public void accept(@NonNull Disposable disposable) throws Exception {
                                if (view != null) {
                                    view.showLoadingView();
                                }
                            }
                        })
                        .subscribeOn(AndroidSchedulers.mainThread())
                        .observeOn(AndroidSchedulers.mainThread())
                        .doFinally(new Action() {
                            @Override
                            public void run() throws Exception {
                                if (view != null) {
                                    view.hideLoadingView();
                                }
                            }
                        });
            }
        };
    }
```

### 2、取消请求的方法已经加上了，详细用法可以阅读文档
