### ISSUE TITLE
您好, 请问每次请求都无限制的 New  Retrofit 和 OkHttpClient，是出于什么考虑呢？

### ISSUE THREAD

**Issue by JessYanCoding** [lygttpod/RxHttpUtils#21]
您好，打扰了，无意中看到您的库，粗略的学习了下您的代码，发现您的框架可以使用两种模式进行网络请求

第一种模式持有全局唯一的 **Retrofit.Builder** 对象和 **OkHttpClient.Builder** 对象，每次网络请求都调用一次 **build()** 方法生成新的 **Retrofit** 对象 和 **OkHttpClient** 对象，再调用 **create()** 生成新的 **APIService** 对象进行网络请求

第二种模式，每次网络请求都 **New** 一个 **Retrofit.Builder** 对象和 **OkHttpClient.Builder** 对象，进行 **Retrofit** 和 **OkHttpClient** 的参数配置后再分别调用一次 **build()** 方法生成新的 **Retrofit** 对象 和 **OkHttpClient** 对象，再调用 **create()** 生成新的 **APIService** 对象进行网络请求

可以看到两种模式在每次请求中都会重新生成新的 **Retrofit** 对象和 **OkHttpClient** 对象，意味一个使用您这个库的 **App** 为了请求数据会无限制的重复生成新的 **Retrofit** 对象和 **OkHttpClient** 对象

而且这些 **Retrofit** 对象和 **OkHttpClient** 对象大多数情况配置可能都是一样的，需要使用到多个 **Retrofit** 的场景, 大多都是需要多 **BaseUrl** 进行不同域名请求的情况，但是可以通过 [RetrofitUrlManager](https://github.com/JessYanCoding/RetrofitUrlManager) 重复使用同一个 **Retrofit** 就可以解决

在我的项目中调用 **create()** 生成的 **APIService** 都是全局唯一的，重复请求只会使用同一个 **APIService**，所以我不明白您为什么需要每次请求网络都需要新建这些对象，App 在进行高频率的网络请求时会出现性能上的损耗吗, 这样做，还是有什么其他的考虑？

### 感谢您对开源软件做出的贡献，提这个 **Issues** 只是为了学术交流，如果冒犯到您，请见谅!

**Comment by cocowobo** [comment]
同问，楼上的是个美女。加个微信呗

**Comment by lygttpod** [comment]
>  ### 首先欢迎技术交流！

*  期初是想着把ApiService也封装进去，暴露出get 、post 等方法给用户，但实际在我开发使用过程中发现，ApiService 里有很多种书写方式要根据后台去书写，比如form表单格式，json格式的等等，如果我封装的时候加进去对用户的灵活性就不高，如果是自己使用，完全可以这样按照你的说的把APIService 封装成全局的，因为自己的后台是固定的。但考虑到既然是开源出去，那么其他开发者的后台和自己的会不一样，如果还按照常规的写，会出现对部分用户不兼容问题，这个也有用户反馈过 ，所以就把ApiService 的权限交给开发者去处理，就没有把ApiService 封装进去，这样就会出现你描述不是全局对象的问题。

*  至于动态修改baseUrl的问题之前也看过你发的[RetrofitUrlManager](https://github.com/JessYanCoding/RetrofitUrlManager)的作者写的关于[解决Retrofit多BaseUrl及运行时动态改变BaseUrl](https://www.jianshu.com/p/2919bdb8d09a)的文章介绍，我这里暂时是以一种最简单粗暴的方式使用SingleRxHttp每次new新的 Retrofit.Builder对象去处理的（毕竟一个项目大部分请求都是统一的，能使用到修改baseUrl的请求的情况不多，所以这点性能影响几乎可以忽略，我就暂时这样处理了（其实是偷懒，哈哈）），我这边水平有限所以封装的不是很完美，还有很多不足之处，欢迎指正。

**Comment by lygttpod** [comment]
> 大写的尴尬才发现你就是该库及那篇文章的作者，那篇文章写得很好，受教了

**Comment by JessYanCoding** [comment]
感谢作者的回复! 
**ApiService** 在我的框架中, 也是让开发者自己设计的, 也没有固定封装到框架中, 只是建了一个缓存所有 **ApiService** 的存储空间, 用户调用同样的接口返回 **ApiService**, 只是如果这个 **ApiService** 是开发者之前使用过, 有缓存的, 我就返回缓存的 **ApiService**, 如果是第一次使用 **ApiService** 就新建并且将它缓存, 用户照样可以自定义 **ApiService**, 但框架却能管理用户自定义的 **ApiService**

还有其实 **ApiService** 不是全局我能理解,  **Retrofit**  不是全局我也能理解，但是 **OkHttpClient** 不是全局我就不能理解了, 重复创建 **Retrofit** 是因为为了处理多 **BaseUrl**,  但重复创建 **OkHttpClient** 我就不理解是为了应对什么场景了, 毕竟需要用到多个不同配置的 **OkHttpClient**  对象的应用场景可能比项目中出现多个 **BaseUrl** 的几率还小的多,

而且您不管什么情况(哪怕 **BaseUrl** 是一致的)默认所有请求都不断的重复创建 **Retrofit** 和 **OkHttpClient** 对象,  开发者只是碎片化的请求网络, 性能影响可能不大, 但是如果多次并且高频率的请求网络, 性能多多少少应该还是有影响的

**Comment by lygttpod** [comment]
很高兴您能指出项目中目前存在的问题，当初开发时候可能没想那么多，目前确实会重复创建对象，我这边会做一些优化处理。

回头也好好研读一下您的框架，学习一下。

**Comment by lygttpod** [comment]
@JessYanCoding 
打扰一下，向您咨询个技术问题：
我先大概描述一下问题：使用Retrofit发起请求的时候需要配置GsonConverterFactory来让请求返回结果自动转化为JavaBean对象的格式
```
 mRetrofitBuilder = new Retrofit.Builder()
                .addConverterFactory(GsonConverterFactory.create(GsonAdapter.buildGson()));
```
但是有的时候返回的结果不是json的格式，需要我们使用string去接收结果，这个时候使用ScalarsConverterFactory配置即可，如下
```
 mRetrofitBuilder = new Retrofit.Builder()
                .addConverterFactory(ScalarsConverterFactory.create())
                .addConverterFactory(GsonConverterFactory.create(GsonAdapter.buildGson()));
```
那么，如果使用单例Retrofit如何做到针对特殊请求使用不同的CallAdapterFactory纳，或者是有其他比较好的办法处理返回结果是json和string的情况的吗？

**Comment by JessYanCoding** [comment]
**ScalarsConverterFactory** 和 **GsonConverterFactory** 是 **Retrofit** 官方定义的 解析器, **addConverterFactory** 可以将所有解析器放入一个容器中, **Retrofit** 并不是让容器中的所有解析器都对结果解析一遍, 只有当上一个解析器无法解析(解析器中的方法返回 null), 他才会使用容器中的下一个解析器进行解析, 如您上面的代码, 只有 **ScalarsConverterFactory** 处理后结果仍然返回 null, **GsonConverterFactory** 才有机会将结果解析为 **Json**, 什么时候返回 null 这个逻辑是官方定义的, 您的需求无非就是以您自己的业务逻辑判断什么时候返回 null, 什么时候解析后返回 String, 所以您需要自己自定义 **ConverterFactory**, 请自行百度这里的相关知识

**Comment by lygttpod** [comment]
多谢解答！！！

**Comment by puxiaoshuai** [comment]
高手过招
