### ISSUE TITLE
关于缓存，和取消请求

### ISSUE THREAD

**Issue by LLQQHH** [lygttpod/RxHttpUtils#22]
1.可否自定义缓存，因为自带你的缓存，必须是get请求而且还需要服务器配合头文件返回处理
2.可否用：Rxlifecycle取消请求

**Comment by lygttpod** [comment]
取消请求 已提供相关方法，具体使用请查看文档或  [更新日志](https://github.com/lygttpod/RxHttpUtils/releases)
