### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by LLQQHH** [lygttpod/RxHttpUtils#24]
有缓存会走onSuccess方法，但是如果需求是，
1.先取缓存，无论如何都去取网络的，您这个框架怎么做！
2.先取缓存，缓存没数据，再去网络的，您这个框架怎么做！
小白一个，可否讲个思路

**Comment by xuhuanli** [comment]
可以参考okhttp的缓存拦截器

**Comment by lygttpod** [comment]
目前支持的缓存策略如下：

1、有网 ：
* 没开启缓存 每次都走网络
* 开启缓存，第一次走网络，拿到数据缓存60秒（默认），下次无论有没网都先度缓存，如果缓存到期走网络，否则只读缓存

2、无网：
* 没开缓存，走网络，返回网络错误信息
* 开启缓存，先度缓存，如果没找到缓存，返回504，就起动网络路线，返回网络错误信息；否则读取缓存信息
