### ISSUE TITLE
超时时间有问题

### ISSUE THREAD

**Issue by FrankLove** [lygttpod/RxHttpUtils#26]
请问在请求数据的时候我这边返回的是一个list数组，但是数据为空的时候返回的是
{"error":"0","data":null}
定义的调用接口是
Observable<List<LiveBean>> getLive(@Query("params") int id);
这样的话数据为空的话就会报错
onError: errorMsg Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
请问有什么办法处理这种情况吗

**Comment by lygttpod** [comment]
我这边data有时候也会返回null   但用list接受没问题   可以加下QQ群  私聊帮你联调一下

**Comment by FrankLove** [comment]
@lygttpod 好的，多谢
