### ISSUE TITLE
清单文件合并冲突

### ISSUE THREAD

**Issue by xuhuanli** [lygttpod/RxHttpUtils#29]
library的清单文件里面android:allowBackup="true" 导入的时候无法合并(我在本地禁用了备份功能)  能把这个属性从manifest里面删除吗

**Comment by lygttpod** [comment]
这还能影响？是不是里边的权限配置冲突了？

**Comment by xuhuanli** [comment]
我这边android:allowBackup="false"  library里面设置成了true build合并时候就起了冲突

**Comment by lygttpod** [comment]
allowBackup即使删除了   如果在你主项目中设为false的话还是回报合并错误的，因为allowBackup默认是true

```
Error: Attribute application@allowBackup value=(false)
 from AndroidManifest.xml:41:9-36 is also present
 at AndroidManifest.xml:12:9-35 value=(true). 
Suggestion: add 'tools:replace="android:allowBackup"' to <application> element
 at AndroidManifest.xml:39:5-360:19 to override. app main manifest (this file), line 40 
```
使用tools:replace="android:icon, android:theme,android:allowBackup"即可

[参考这篇文章](https://blog.csdn.net/bgc525725278/article/details/71171241)
