### ISSUE TITLE
BaseObserver 对HttpException 比如404、500 等处理后error 信息获取为空字符串

### ISSUE THREAD

**Issue by xiangxm** [lygttpod/RxHttpUtils#33]
@Override
    public void onError(@NonNull Throwable e) {
        String error = ApiException.handleException(e).getMessage();
        setError(error);
    }

这里的error 取出来的数据是”“ 空字符串。

希望可以添加上信息提示

**Comment by lygttpod** [comment]
问题已修复  [更新日志](https://github.com/lygttpod/RxHttpUtils/releases)

**Comment by xiangxm** [comment]
辛苦了
