### ISSUE TITLE
cache的空指针异常问题

### ISSUE THREAD

**Issue by FlogFly** [lygttpod/RxHttpUtils#36]
目前不管是否设置了cache缓存，第一句一定会去执行，然后就有可能报空指针异常。
private void setCacheConfig() {
            OkHttpConfig.defaultCachePath = this.context.getExternalCacheDir().getPath() + "/RxHttpCacheData";
            if (this.isCache) {
                Cache cache;
                if (!TextUtils.isEmpty(this.cachePath) && this.cacheMaxSize > 0L) {
                    cache = new Cache(new File(this.cachePath), this.cacheMaxSize);
                } else {
                    cache = new Cache(new File(OkHttpConfig.defaultCachePath), 104857600L);
                }

                OkHttpConfig.okHttpClientBuilder.cache(cache).addInterceptor(new NoNetCacheInterceptor()).addNetworkInterceptor(new NetCacheInterceptor());
            }

        }

里面的第一句，如果设备获取getExternalCacheDir是null,那么后面还会执行getpath，然后就报空指针异常了。

**Comment by lygttpod** [comment]
# getExternalCacheDir确实有可能会为null，没考虑全，感谢提出问题，会尽快修复的

![image](https://user-images.githubusercontent.com/11826777/46936183-21753e80-d090-11e8-82c7-d229d7fca4ff.png)

**Comment by lygttpod** [comment]
新版本已修复
