### ISSUE TITLE
动态修改header的问题！！ 求解

### ISSUE THREAD

**Issue by DevXue** [lygttpod/RxHttpUtils#37]
#31   我按照大神这里头指导的设置了到了本地 存文件的方式
我的需求也是 登录之后 服务器会给返回token的值，通过json给我返回 然后我保存到了SP文件中，  我的请求头的键为 access-token，值就是服务器返回的，    我在全局APPlication设置了  但是不知道此时的值该怎么设置···    我测试通过登录后返回了token  然后保存到了SP中，可是当我请求另外一个接口的时候  access-token就没有传递···
![l5 4xe k0 7 cvl66b0f4 8](https://user-images.githubusercontent.com/9455329/47078441-e745a180-d235-11e8-9af7-72c2f179106b.png)

![2222](https://user-images.githubusercontent.com/9455329/47078559-23790200-d236-11e8-9b97-84fbccebaf6f.png)

**Comment by lygttpod** [comment]
# 仿照上边的你自定义一个拦截器  里边获取参数修改成获取你存入本地的token即可
![image](https://user-images.githubusercontent.com/11826777/47127190-ac3b8080-d2be-11e8-84a4-bc1984df8d49.png)

**Comment by lygttpod** [comment]
动态修改header问题已在V2.2.0中优化，可阅读[V2.2.0更新说明](https://github.com/lygttpod/RxHttpUtils/releases/tag/2.2.0)了解
