### ISSUE TITLE
上传单张图片的时候，之前配置好的HeaderInterceptor中的参数没有生效

### ISSUE THREAD

**Issue by w4mxl** [lygttpod/RxHttpUtils#38]
库开发者您好，在使用
  /**
     * 上传单张图片
     *
     * @param uploadUrl  地址
     * @param uploadPath 文件路径
     */
    private void uploadImg(String uploadUrl, String uploadPath) {

        RxHttpUtils.uploadImg(uploadUrl, uploadPath)
                .compose(Transformer.<ResponseBody>switchSchedulers(loading_dialog))
                .subscribe(new CommonObserver<ResponseBody>() {

                    @Override
                    protected String setTag() {
                        return "uploadImg";
                    }

                    @Override
                    protected void onError(String errorMsg) {
                        Log.e("allen", "上传失败: " + errorMsg);
                        showToast(errorMsg);
                    }

                    @Override
                    protected void onSuccess(ResponseBody responseBody) {
                        try {
                            String msg = responseBody.string();
                            showToast(msg);
                            Log.e("allen", "上传完毕: " + msg);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    }
                });

    }
的时候发现之前定义好的header中的参数没有传递给服务端。其它的接口请求是正常传递header参数的。
请问这种情况下应该怎么处理呢？

**Comment by lygttpod** [comment]
库里边上传图片是单独的，和正常请求的全局配置是分开的，如果有需求要和全局配置统一的话，就把上传图片的逻辑拷一份，自己写个上传的方法就行了

**Comment by w4mxl** [comment]
> 库里边上传图片是单独的，和正常请求的全局配置是分开的，如果有需求要和全局配置统一的话，就把上传图片的逻辑拷一份，自己写个上传的方法就行了

好的，感谢回复。真的好迅速 👍

**Comment by Lion7k** [comment]
请问把上传图片和全局配置合起来是怎么弄的

**Comment by lygttpod** [comment]
@liuzq8769 和单独上传图片一样的逻辑，只不过是公用一个Retrofit对象，和正常使用全局配置一样定义方法，参数就是上传图片的参数即可

**Comment by lygttpod** [comment]
可以看下新版本 2.1.7  
参考demo
