### ISSUE TITLE
多个接口请求后回调回来  区分的问题！

### ISSUE THREAD

**Issue by DevXue** [lygttpod/RxHttpUtils#39]
比如我的Activity要发起 5 次接口请求，而且是没有关联的请求，    我同时发起，然后回调回来(我的请求是在Model层发起的，Activity只管处理回调方法)

**Model层发起请求 1**
```java



 RxHttpUtils
                .createApi(API.class)
                .getData(pn,ps,type)
                .compose(Transformer.<Rtn>switchSchedulers(DialogUtil.showLoading(context)))
                .subscribe(new CommonObserver<Rtn>() {

                    @Override
                    protected void onError(String errorMsg) {
                        onResponseFailed(null,errorMsg);
                    }

                    @Override
                    protected void onSuccess(Rtn bookBean) {
                        onResponseSuccess(code,bookBean);    //这里是Activity 复写的回调方法
                    }
                });


**Model层发起请求 2*·

RxHttpUtils
                .createApi(API.class)
                .getData(pn,ps,type)
                .compose(Transformer.<Rtn>switchSchedulers(DialogUtil.showLoading(context)))
                .subscribe(new CommonObserver<Rtn>() {

                    @Override
                    protected void onError(String errorMsg) {
                        onResponseFailed(null,errorMsg);
                    }

                    @Override
                    protected void onSuccess(Rtn bookBean) {
                        onResponseSuccess(code,bookBean);  //这里是Activity 复写的回调方法
                    }
                });

**Model层发起请求 3**

RxHttpUtils
                .createApi(API.class)
                .getData(pn,ps,type)
                .compose(Transformer.<Rtn>switchSchedulers(DialogUtil.showLoading(context)))
                .subscribe(new CommonObserver<Rtn>() {

                    @Override
                    protected void onError(String errorMsg) {
                        onResponseFailed(null,errorMsg);
                    }

                    @Override
                    protected void onSuccess(Rtn bookBean) {
                        onResponseSuccess(code,bookBean);  //这里是Activity 复写的回调方法
                    }
                });

这里的R小HttpUtils中的onSuccess 中写了个onResponseSuccess() 方法， 我咋我的Activity中复写这个方法  就可以接受回调回来的数据， 那么此时 我该怎么区分  是哪个接口回来的请求呢？

**Comment by lygttpod** [comment]
在你的onResponseSuccess回调方法中加个参数就可以实现
比如 onResponseSuccess( type, code, bookBean),因为你的请求中已经有type参数区分了，直接回调回来就好了

**Comment by DevXue** [comment]
好的  谢谢你！

**Comment by qiongqiong-wu** [comment]
不好意思，我一菜鸟，不太了解，请问可以写的具体些吗？

**Comment by DevXue** [comment]
@wq1216 
我个人的做法 仅供参考：
```java
 下面这段代码比如你在Activity里头调用了 getData的方法来请求数据，
那么这个时候 你可以通过这个方法中的type参数来区分你的接口，比如这是一个获取用户信息的接口，这个type 的值为“getUser” , 然后你又发起了一个获取用户地址的接口为getAddressData(String type) ,此时这个type的值为“getAddress” ,那么你在回调中判断这个type即可 就知道这个那个请求的回调了，  我个人是这么搞得，又掉low···

  public void getData(int pn,int ps,type){
    RxHttpUtils
                .createApi(API.class)
                .getData(pn,ps,type)
                .compose(Transformer.<Rtn>switchSchedulers(DialogUtil.showLoading(context)))
                .subscribe(new CommonObserver<Rtn>() {

                    @Override
                    protected void onError(String errorMsg) {
                        onResponseFailed(null,errorMsg);
                    }

                    @Override
                    protected void onSuccess(Rtn bookBean) {
                        onResponseSuccess(code,bookBean);  //这里是Activity 复写的回调方法
                    }
                });

  }
```

**Comment by wq1216** [comment]
@DevXue  请问你是自己又重新封装RxHttpUtils的吗？

**Comment by wq1216** [comment]
public void requestFilm() {
		params1.put("appid", "3621c6797b384f93e6d80163952f481f");
		params1.put("mid", "228514");
		RequestHandler.request(1, params1).compose(Transformer. <String>switchSchedulers(
				loading_dialog))
				.subscribe(new CommonObserver <String>() {
					@Override
					protected void onError(String errorMsg) {
						showToast(errorMsg.toString());
					}

					@Override
					protected void onSuccess(String s) {
						Log.e("***************", s);
						Gson gson = new Gson();
						Film film = new Film();
						film = gson.fromJson(s, Film.class);
						int code = film.getError_code();
						if (code == 0) {
							Film.DataBean dataBean = film.getData();
							mResponseData.setText(dataBean.toString());
						} else {
							showToast(code + film.getReason());
						}
					}
				});
	}

	public void requestMovies() {
		params2.put("appid", "4f8b3d9341639f3bd63118a118b7ee17");
		RequestHandler.request(2, params2)
				.compose(Transformer. <String>switchSchedulers(
						loading_dialog))
				.subscribe(new CommonObserver <String>() {
					@Override
					protected void onError(String errorMsg) {
						showToast(errorMsg.toString());
					}

					@Override
					protected void onSuccess(String list) {
						ResponseHandler responseHandler = new ResponseHandler();
						Gson gson = new Gson();
						Movie movie = new Movie();
						movie = gson.fromJson(list, Movie.class);
						int code = movie.getError_code();
						if (code == 0) {
							List <Movie.DataBean> dataBeans = movie.getData();
							ListAdapter listAdapter =
									new ListAdapter(QuestActivity.this, dataBeans);
							mListData.setAdapter(listAdapter);
						} else {
							showToast(code + movie.getReason());
						}
					}
				});
	}





@DevXue 请问我这还可以在封装一下吗？
