### ISSUE TITLE
取消全部请求的问题

### ISSUE THREAD

**Issue by aellenlei** [lygttpod/RxHttpUtils#43]
版本号:2.1.7
描述:使用RxHttp时，调用RxHttpUtils.canceAll(),也就是取消全部请求时，APP崩溃了，直接错误是 java.util.ConcurrentModificationException,日志定位到RxHttpManager.java这个文件的第97行，
可能原因：
> @Override
    public void cancelAll() {
        if (mMaps.isEmpty()) {
            return;
        }
        Iterator<Map.Entry<Object, CompositeDisposable>> it = mMaps.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry<Object, CompositeDisposable> entry = it.next();
            Object tag = entry.getKey();
            cancel(tag);
        }
    }
迭代HashMap()时，同时调用了cancel()这个方法，而这个方法里面有调用了HashMap的remove方法，导致ConcurrentModificationException。

**Comment by lygttpod** [comment]
2.1.8版本已修复
