### ISSUE TITLE
请问缓存默认60秒如何修改为其他时间

### ISSUE THREAD

**Issue by zgnckzn** [lygttpod/RxHttpUtils#44]
大神晚上好，我们的需求需要把缓存的60秒改为10秒，拜读了大神的代码，没有找到可以修改的函数。于是copy了一份OkHttpConfig，又copy了一份NetCacheInterceptor，把默认的60秒改为10秒，Copy的OkHttpConfig中使用新的NetCacheInterceptor进行拦截，然后按照原来的OkHttpConfig的使用方式来使用，经测试，发现拦截器全都不好使了，想咨询一下大神，我的问题大概出在哪里？是否有更加简单的修改默认60秒的方法。期待大神回复，感谢大神提供的工具，真的很方便

**Comment by lygttpod** [comment]
由于近期有很多私事要处理，所有问题目前只做记录汇总，我会在下个月统一处理issues提的问题。给你带来不便还请谅解！


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by lygttpod** [comment]
你是要修改有网的时候的缓存时间呐还是修改没网的时候的缓存时间

**Comment by zgnckzn** [comment]
修改有网络时候的缓存时间，无网络的时候可以用默认的。如果都能修改，应该更灵活。先谢大神了

**Comment by lygttpod** [comment]
方便的话加群私聊，我这边需要你帮忙测试一下

**Comment by zgnckzn** [comment]
已加群，明天群内联系，感谢作者大神。

**Comment by lygttpod** [comment]
问题已修复，请查看[V2.2.0更新说明](https://github.com/lygttpod/RxHttpUtils/releases)
