### ISSUE TITLE
同一个请求如果请求的间隔时间很短，不同的标题头参数会请求到相同的数据是怎么回事呢？

### ISSUE THREAD

**Issue by abiaodev** [lygttpod/RxHttpUtils#46]

**Comment by lygttpod** [comment]
看下打印的日志里边两次请求所以参数是否一样


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by abiaodev** [comment]
我打印过了，确实是不一样的，可能是缓存的问题，我把全局配置的setCache设置为false的时候请求就不再时上一次的结果了。

**Comment by lygttpod** [comment]
那就是数据缓存了，缓存是根据URL判断的，URL相同就会认为是同一个请求进行处理

**Comment by abiaodev** [comment]
原来是根据URL来判断的，能不能解决请求头变更之后请求也变更呢？

**Comment by xiangxm** [comment]
我也遇到这个问题，在缓存存活时间内，再次发起请求数据一样。
