### ISSUE TITLE
有无统一回调处理的？比如后台返回code-1的话就跳到登录界面，这样，不必每个接口都处理。

### ISSUE THREAD

**Issue by yuxingfafu** [lygttpod/RxHttpUtils#53]
有无统一回调处理的？比如后台返回code-1的话就跳到登录界面，这样，不必每个接口都处理。

**Comment by lygttpod** [comment]
## 有啊，参照DataObserver实现自己的DataObserver需要的逻辑就行

![image](https://user-images.githubusercontent.com/11826777/54597550-b4683980-4a71-11e9-918c-1e946f3e3d3c.png)
