### ISSUE TITLE
想了解用这个框架遇到activity或fragment已经退出后，回调才返回，更新UI导致的空指针问题有没有优雅的解决办法

### ISSUE THREAD

**Issue by zgnckzn** [lygttpod/RxHttpUtils#54]
RxHttpUtils
                 .createApi(ApiService.class)
                 .getTestData()
                 .compose(Transformer.<TestBean>switchSchedulers())
                 .subscribe(new CommonObserver<TestBean>() {

                     @Override
                     protected void onError(String errorMsg) {
                          //错误处理
                     }

                     @Override
                     protected void onSuccess(TestBean bookBean) {
                          //业务处理，根据结果更新UI，如果activity或fragment已经销毁，此时通常都会发生空指针异常，请问有没有统一的，优雅的解决方法

                     }
                  });

**Comment by Iverlei** [comment]
自己去绑定RxLifecycle就可以了

**Comment by lygttpod** [comment]
## [关于取消请求请看v2.1.3更新说明](https://github.com/lygttpod/RxHttpUtils/releases/tag/2.1.3)

* ### 可以在onDestroy方法中调取取消请求的方法


`

                //调取如下方法取消某个或某组请求
                RxHttpUtils.cancel("yourTag");

                //调取如下方法取消多个或多组请求
                RxHttpUtils.cancel("yourTag1","yourTag2","yourTag3");
`

**Comment by zgnckzn** [comment]
多谢大神指导，经试验，闪退概率小多了，但偶尔还是会出现，可能还是存在时间差。

**Comment by zgnckzn** [comment]
> 自己去绑定RxLifecycle就可以了

我的Activity和Fragment已经继承其他的库了
