### ISSUE TITLE
HTTPS不验证证书请求失败，提示javax.net.ssl.SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by liuhanling** [lygttpod/RxHttpUtils#55]
经过验证是未添加hostnameVerifier导致，OkhttpConfig中没有对应的方法，建议添加。
其实在SSLUtils类中已有定义，只是未使用：
public static HostnameVerifier UnSafeHostnameVerifier = new HostnameVerifier() {
        @Override
        public boolean verify(String hostname, SSLSession session) {
            return true;
        }
 };

**Comment by lygttpod** [comment]
> 从 2017 年 3 月 1 日起，只要新应用或应用更新采用的 HostnameVerifier 的实施方式不安全，一律禁止在 Google Play 发布。您已发布的APK版本不会受到影响，但是，如果不解决此漏洞，您将无法为应用发布任何更新

使用HostnameVerifier直接返回true也会被Google Play检测不安全，所有代码中就没设置了，如果有这方面需求我可以在OkhttpConfig中提供个方法设置开发者自己的HostnameVerifier

**Comment by lygttpod** [comment]
V2.3.1  OkHttpConfig新增SetHostnameVerifier方法，并增加默认实现
