### ISSUE TITLE
当我使用downloadFile下载文件时候出现错误

### ISSUE THREAD

**Issue by Iverlei** [lygttpod/RxHttpUtils#56]
我使用你的dome中的下载部分（downloadFile）， 当我更换一个url时候 (http://www.23read.cn/data/upload/txt/20190118/15477827110.txt)，下载会出错，在onSuccess回调中 progress会变成一个很大的负数比如-2000000，done也不会返回true

**Comment by lygttpod** [comment]
问题已修复[V2.3.2](https://github.com/lygttpod/RxHttpUtils/releases/tag/2.3.2)
