### ISSUE TITLE
更新sdk到最新后遇到的bugs

### ISSUE THREAD

**Issue by CJEEP** [lygttpod/RxHttpUtils#57]
更新sdk 到最新后，发现问题：
1.文件下载过程点击取消下载失效；
2.上传功能集体罢工，点击崩溃。
优化建议：
是否考虑采用rxlifecycle 来处理Retrofit生命周期的管理优化呢？

**Comment by lygttpod** [comment]
1、对于上述两个问题：demo测试没出现问题
2、对于优化建议：本库只是网络请求库，责任明确，关于生命周期的处理不是所有人都愿意使用RxLifecycle库，毕竟LiveData也可以完美处理生命周期问题，所以对此问题交给开发者自己选择，不在库中依赖。

> 如果你那边还会出现描述中的bug，麻烦入群讨论，谢谢支持

**Comment by CJEEP** [comment]
好的，谢谢。
