### ISSUE TITLE
  RxUrlManager.getInstance().addUrl("urlKey", "urlValue");

### ISSUE THREAD

**Issue by wupengwp** [lygttpod/RxHttpUtils#58]
RxUrlManager.getInstance().addUrl("urlKey", "urlValue");这个在初始化之后动态添加url，无效，比如需求需要手动配置ip地址，之前版本RxHttpUtils.getSInstance().baseUrl(BASE_URL)可以，现在该怎么设置？

**Comment by lygttpod** [comment]
RxUrlManager.getInstance().addUrl("urlKey", "urlValue")和setMultipleUrl()都是项目有对个url时候使用的，单url可以使用RxUrlManager.getInstance().setUrl("urlValue")

**Comment by wupengwp** [comment]
RxUrlManager.getInstance().setUrl("urlValue")这个在全局初始化配置好之后使用可以更改全局配置的url吗？

**Comment by wupengwp** [comment]
RxUrlManager.getInstance().setUrl("urlValue")在初始化全局配置后修改，改成功了，但是使用全局配置的请求失败

**Comment by wupengwp** [comment]
RxUrlManager.getInstance().clear(); ApiFactory.getInstance().clearAllApi();找到了，需要这么设置下

**Comment by lygttpod** [comment]
这个问题我记录一下 周末发新版，以后调RxUrlManager.getInstance().setUrl("urlValue")切换url之后就不用调clearAllApi()方法了

**Comment by lygttpod** [comment]
代码已优化[V2.3.3更新说明](https://github.com/lygttpod/RxHttpUtils/releases/tag/2.3.3)
```
RxUrlManager.getInstance().clear().setUrl("baseUrl");
```
