### ISSUE TITLE
token过期失效处理，网络请求失败后点击再次请求

### ISSUE THREAD

**Issue by chenxiaofei910714** [lygttpod/RxHttpUtils#59]
1.登录之后token存在sp文件放在在拦截器的设置请求头里，如果一个页面需要请求多个接口，每个接口都需要token，返回结果自定义code 或者http的code码异常时，怎么处理刷新token后再去请求当前的接口
2.对于网络请求有多状态页面的界面，网络错误后，点击重试请求当前接口时怎么处理呢

**Comment by lygttpod** [comment]
1、刷新token：
在拦截器里边Interceptor通过response.code()判断是否过期，过期的话发送同步请求刷新token，把新的token设置到head中即完成刷新token
2、请求重试：
点击重试就重新调一下接口就行了吧
