### ISSUE TITLE
setRightString 会出现 ellipsize

### ISSUE THREAD

**Issue by billsinla** [lygttpod/RxHttpUtils#6]
用代码设置 setRightString
会出现
![8 16yi5 jkony 5n8 k7](https://user-images.githubusercontent.com/15274049/29345700-04c2b9a0-8273-11e7-9d83-b44e0f700ae4.png)

会自动ellipsize

**Comment by lygttpod** [comment]
@billsinla 请使用最新版本  2.1.2

**Comment by lygttpod** [comment]
@billsinla 大兄弟，提的issues搞错项目了吧，哈哈

**Comment by billsinla** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈，扎心了
