### ISSUE TITLE
单个请求如何动态设置超时时间

### ISSUE THREAD

**Issue by CaiJinFu** [lygttpod/RxHttpUtils#60]
单个下载，上传，或者post，get请求时，怎么设置临时的超时时间？

**Comment by lygttpod** [comment]
![image](https://user-images.githubusercontent.com/11826777/56937457-5da15580-6b2f-11e9-8d0d-29c6d03e93a8.png)

**Comment by CaiJinFu** [comment]
不会影响在application中设置全局的配置吧

**Comment by lygttpod** [comment]
都是单个请求了  已经和全局没关系了  okhttpclient都是自己新建的了，没使用全局的okhttpclient
