### ISSUE TITLE
json被截断导致list<bean>不能转换

### ISSUE THREAD

**Issue by molele2** [lygttpod/RxHttpUtils#61]
ApiHelper.getVenusApi()
                       .getTrend("车模",0,30)
//                    .compose(new DefaultTransformer<List<Trend>>switchSchedulers(loading_dialog))
                       .compose(Transformer.<BaseData<List<Trend>>>switchSchedulers(loading_dialog))
                       .subscribe(new DataObserver<List<Trend>>() {
                           @Override
                           protected void onError(String errorMsg) {

                           }

                           @Override
                           protected void onSuccess(List<Trend> data) {
//                               responseTv.setText(JSON.toJSONString(data));
//                               showToast(data.get(0).getTitle());
                           }
                       });

返回json被截断
{
    		"nickname":"天魔",
    		"avatar":"https://img.gsdlcn.com/uploads/180823/13-1PR314105B17.jpg",
    		"objectList":[
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3141049-50.jpg",
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3141049-51.jpg",
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3141050.jpg",
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3141050-50.jpg",
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3141050-51.jpg",
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3141050-52.jpg",
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3141050-53.jpg"
    		]
    	},
    	{
    		"nickname":"天魔",
    		"avatar":"https://img.gsdlcn.com/uploads/180823/13-1PR3140546332.jpg",
    		"objectList":[
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3140538-50.jpg",
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3140538-51.jpg",
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3140539.jpg",
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3140539-50.jpg",
    			"https://img.gsdlcn.com/uploads/allimg/180823/13-1PR3140539-51.jpg",
    			"htt
I/Toast: Show toast from OpPackageName:com.warunion.study, PackageName:com.warunion.study

导致解析出错

**Comment by lygttpod** [comment]
加QQ群，帮你联调

**Comment by molele2** [comment]
长数据转换的时候被截断，这个问题我以前解决过，时间太长忘记当时怎么解决的了，

**Comment by lygttpod** [comment]
能否加群私聊，我想深入了解一下这个问题
