### ISSUE TITLE
希望楼主改进下请求或者返回日志显示不全的问题

### ISSUE THREAD

**Issue by GuilinSir** [lygttpod/RxHttpUtils#64]

**Comment by lydlovezjr** [comment]
+1

**Comment by lygttpod** [comment]
* 返回结果日志信息只是辅助参考数据（日志打印长度本身也是有限制的）

确定自己的需求：
1、单纯的看请求的全部数据
2、根据数据建bean
* 如果是第一种需求，数据量不较大，可以使用postman这种专业模拟请求的工具查看
* 如果是第二种需求你，也可以使用postman，或者请求的时候就只获取第一个第一条列表数据即可，这样的话就一定可以看到打印的完整数据（除非你们一条数据就有几百个字段才会显示不完整），没必要一定要把第一个20条数据都拿到才能建bean
