### ISSUE TITLE
设置图片位置的一些建议

### ISSUE THREAD

**Issue by happy-all** [lygttpod/RxHttpUtils#65]
网络图片只能设置左边和右边，为啥不做完美一点呢？上面和下面也弄呀，就像设置text属性那样严谨，上下左右，左上，左下，中上，中下，右上右下。

**Comment by lygttpod** [comment]
大兄弟Issues提错项目了吧，这里是 [RxHttpUtils](https://github.com/lygttpod/RxHttpUtils) 不是[SuperTextView](https://github.com/lygttpod/SuperTextView)
