### ISSUE TITLE
切换BaseUrl后请求就全部报错了，如果不切换，是正常的

### ISSUE THREAD

**Issue by MapleSunFLY** [lygttpod/RxHttpUtils#67]

**Comment by lygttpod** [comment]
请提错误日志信息及全局配置代码和切换URL相关代码

**Comment by MapleSunFLY** [comment]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
     <html>
     <head><title>400 Bad Request</title></head>
     <body>
     <center><h1>400 Bad Request</h1></center>
     <hr><center>tengine</center>
     </body>
     </html>

ApiFactory.getInstance().setBaseUrl(configMeta.getHost()).clearAllApi();

**Comment by MapleSunFLY** [comment]
请求所有接口都报，这个错误，
