### ISSUE TITLE
封装RxObserver

### ISSUE THREAD

**Issue by JerryAlexLiang** [lygttpod/RxHttpUtils#69]
如果服务器返回格式不是BaseData那样的
![image](https://user-images.githubusercontent.com/19645879/63689227-faed6b80-c83b-11e9-808b-1d3a13a9c777.png)
而是其他字段，怎么封装使用呢？
![image](https://user-images.githubusercontent.com/19645879/63689259-135d8600-c83c-11e9-984d-12d144746116.png)

**Comment by lygttpod** [comment]
自己写一个类继承BaseObserver即可，可以参照DataObserver写法

**Comment by JerryAlexLiang** [comment]
OK 谢谢，已看了




------------------ 原始邮件 ------------------
发件人: "Allen"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 下午5:57
收件人: "lygttpod/RxHttpUtils"<RxHttpUtils@noreply.github.com>;
抄送: "晚风轻轻-遮住的岁月Jerry"<1935990239@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lygttpod/RxHttpUtils] 封装RxObserver (#69)




自己写一个类继承BaseObserver即可，可以参照DataObserver写法
