### ISSUE TITLE
下载进度是负数

### ISSUE THREAD

**Issue by Tang3210** [lygttpod/RxHttpUtils#71]
![image](https://user-images.githubusercontent.com/47552566/65010199-aa03fb00-d941-11e9-9625-d37dd6714599.png)

**Comment by lygttpod** [comment]
方便的话，提供一下你的下载地址，我测试一下

**Comment by Tang3210** [comment]
浏览器下载也没有进度条，不知道什么问题。下载别人几百兆的都没问题

**Comment by lygttpod** [comment]
那应该就是文件本身的问题了
