### ISSUE TITLE
下载文件时如何指定连接超时时间

### ISSUE THREAD

**Issue by zgnckzn** [lygttpod/RxHttpUtils#80]
你好，我使用的2.1.9版本
使用RxHttpUtils .downloadFile(String fileUrl)方法下载文件，由于服务器速度比较慢，请问如何更改连接超时、读取超时、写入超时时间？
目前使用如下方式进行的全局处理，不知道是否有效，请指点。
OkHttpClient okHttpClient = new OkHttpConfig.Builder(this)
                .setReadTimeout(60)
                .setWriteTimeout(60))
                .setConnectTimeout(60)
                .build();
RxHttpUtils.getInstance()
                .init(getApplication())
                .config()
                .setBaseUrl(Constants.BASE_URL)
                .setOkClient(okHttpClient);

**Comment by lygttpod** [comment]
下载没使用全局参数
![image](https://user-images.githubusercontent.com/11826777/83242567-33f1ac80-a1cf-11ea-946e-b773c8ffc07d.png)
如有需求可以参考图片的写法，自定义下载
