### ISSUE TITLE
不能设置是否重连和重连次数

### ISSUE THREAD

**Issue by CoderLct** [lygttpod/RxHttpUtils#83]
### 源代码
        /**
         * 配置超时信息
         */
        private void setTimeout() {
            okHttpClientBuilder.readTimeout(readTimeout == 0 ? defaultTimeout : readTimeout, TimeUnit.SECONDS);
            okHttpClientBuilder.writeTimeout(writeTimeout == 0 ? defaultTimeout : writeTimeout, TimeUnit.SECONDS);
            okHttpClientBuilder.connectTimeout(connectTimeout == 0 ? defaultTimeout : connectTimeout, TimeUnit.SECONDS);
            okHttpClientBuilder.retryOnConnectionFailure(true);
        }
已经固定为true，不能配置。

**Comment by lygttpod** [comment]
如果封装的OKhttpClient无法满足需求 可以实现自己的okhttpCliet设置到RxHttpUtils中即可
![image](https://user-images.githubusercontent.com/11826777/89761816-d3151780-db21-11ea-8c2f-6286ffb6c6c0.png)

**Comment by CoderLct** [comment]
thanks
