### ISSUE TITLE
加密 打包之后网络请求 返 java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by hksowhat** [lygttpod/RxHttpUtils#88]
接入RxHttps ，本地测试，调试 ，接口请求都是好的，  加密打包之后，再次网络请求，  HttpUtils 直接错误回调 返我   java.lang.reflect.InvocationTargetException。   

用日志跟踪，找到  IException  定位到  错误信息  

 IException("未知错误", e, ERROR.UNKNOWN)

const val UNKNOWN = 1000   未知错误

*******  
这个问题，在我本地调试，都是好的，  只在我加了签名 打包生成APK， 就会出现这个情况 。

打包成APK，不好断点 排查是什么问题。。。  没法定位 具体是因为什么 ，是哪里出的问题

**Comment by lygttpod** [comment]
@hksowhat 是不是签名之后加了混淆 看下是不是自己的数据模型类被混淆了，添加相应混淆代码再试试

**Comment by hksowhat** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lygttpod/RxHttpUtils"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月22日(星期四) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lygttpod/RxHttpUtils] 加密 打包之后网络请求 返 java.lang.reflect.InvocationTargetException (Issue #88)





 
@hksowhat 是不是签名之后加了混淆 看下是不是自己的数据模型类被混淆了，添加相应混淆代码再试试
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.

&nbsp;谢谢！你们回复！

需要加混淆吗&nbsp; ？&nbsp; 目前项目进度， 除了加声网的&nbsp; ，就没其他混淆。

**Comment by hksowhat** [comment]
谢谢！ 找到原因了 ！加了混淆代码 就可以了
