### ISSUE TITLE
线程安全问题

### ISSUE THREAD

**Issue by Way169165** [lygttpod/RxHttpUtils#9]
SingleRxHttp对每个请求单独配置参数存在线程安全问题，因为该对象获取的方式为单例获取，所有获取到的该对象，线程之间还是会共享数据（baseUrl等），一个线程配置改变会影响其他线程的参数。

**Comment by lygttpod** [comment]
SingleRxHttp只在特殊请求时候使用，多个SingleRxHttp是会创建不同OkHttpClient对象
